Textile/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('textile/blog/', include('blogapps.urls')),
                  path('textile/', include('textileapp.urls')),
              ]
              # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapps/urls.py
from django.urls import path, include
from . import views
app_name = 'blogapps'

urlpatterns = [
    path('', views.blogs, name='blog'),
    path('create_blog/', views.create_blog, name='create_blog'),
    path('update_blog/<int:id>/', views.update_blog, name='blog_update'),
    path('delete_blog/<int:id>/', views.delete_blog, name='blog_delete'),
    path('create_comment/<int:id>/', views.create_comment, name='create_comment'),
    path('article/<int:id>/', views.article, name='article'),
    ]

textileapp/urls.py
from django.urls import path, include
from . import views

app_name = 'textileapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.oneitem, name='oneitem'),

    path('<int:id>/delete/', views.delete),
    path('add/', views.add, name='add'),

    path('login/', views.log, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('register/', views.reg, name='register'),
    path('search/', views.search, name='search'),
    path('search/<int:id>/', views.searchitem, name='searchitem'),

    path('blog/', views.blog, name='blog'),
    path('cart/', views.cart, name='cart'),
    path('checkout/<int:id>/', views.checkout, name='checkout'),
    path('delete_cart/<int:id>/', views.delete_cart, name='delete_cart'),
    # path('addtocart/<int:id>/', views.add_to_cart, name='addtocart'),
    # path('coupon/', views.coupon, name='coupon')
]

templates/article.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Breadcrumbs Start
    ================================================== -->

	<section id="topic-header">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<br>
					<br>
					<br>
					<h1>BLOG</h1>
					<p>Latest News and Musings</p>
				</div>	<!-- End of /.col-md-4 -->
				<div class="col-md-8 hidden-xs">
					<ol class="breadcrumb pull-right">
					  	<li><a href="{% url 'textileapp:index' %}">Home</a></li>
					  	<li><a href="{% url 'blogapps:blog' %}">Blog</a></li>
					  	<li class="active">Single Post</li>
					</ol>
				</div>	<!-- End of /.col-md-8 -->
			</div>	<!-- End of /.row -->
		</div>	<!-- End of /.container -->
	</section>	<!-- End of /#Topic-header -->

	<section id="blog">
		<div class="container">
			<div class="row">
				<div class="col-md-9 clearfix">
					<ul class="blog-zone">
					    <li>
					        <div class="blog-icon">
					        	<i class="fa  fa-pencil"></i>
					        </div>
					        <div class="blog-box">
					        	<img src="{{ob.image.url}}" alt="">

					            <div class="blog-post-body clearfix">
						            <a href="">
					            		<h2>{{ob.title}}</h2>
						            </a>
					            	<div class="blog-post-tag">
						            	<div class="block">
						            		<i class="fa fa-clock-o"></i>
						            		<p>{{ob.created_on}}</p>
						            	</div>
						            	<div class="block">
						            		<i class="fa fa-user"></i>
						            		<p>{{ob.author}}</p>
						            	</div>
						            	<div class="block">
						            		<i class="fa fa-tags"></i>
						            		<p>
						            			<a href="">Food Culture</a>,
						            			<a href="">Green Items</a>
						            		</p>
						            	</div>
						            	<div class="block">
						            		<i class="fa fa-comments"></i>
						            		<p>3 Comments</p>
						            	</div>
						            </div>
						            <p>{{ob.content}}</p>
						            <blockquote>
										<div class="block-qoute-by">
					                        <p style="size:60px;">- {{ob.author}} , Author</p>
					                    </div>
					                </blockquote>
<!--					                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde expedita neque excepturi iste cumque! Dolorem, ipsum, totam, culpa ullam dolores qui possimus corrupti suscipit recusandae quam magnam quis eaque incidunt!</p>-->
					            </div>
					        </div>
					    </li>
					</ul>	<!-- End of /.blog-zone -->

					<div class="author-id">
						<div class="media">
							<h5>About The Author</h5>
						  	<img class="media-object pull-left" src="{{ob.author.author_image.url}}" alt="...">
						  	<div class="media-body">
						    	<h6 class="media-heading">{{ob.author}}</h6>
						    	<p>{{ob.author.description}}</p>
						    </div>	<!-- End of /.media-body -->
						</div>	<!-- End of /.media -->
					</div>	<!-- End of /.author-id -->

					<div class="comments-box">
						<h5>{{ob3}} REPSONSES</h5>
						{% for obj in ob2 %}
						<div class="media">
						  	<img class="media-object pull-left" src="{% static 'images/default-author.jpg' %}" alt="...">
						  	<div class="media-body">
						    	<h6 class="media-heading">{{obj.name}}<span> {{obj.date}} </span> <a href=""  class="pull-right">(reply)</a></h6>
						    	<p>{{obj.message}}</p>
						    </div>	<!-- End of /.meida-body -->
						</div>	<!-- End of /.media -->
						{% endfor %}
					</div>

					<div class="leave-comment">
						<h5>LEAVE A COMMENT</h5>
						<form action="{% url 'blogapps:create_comment' ob.id %}" class="form-horizontal" role="form" method="post">
							{% csrf_token %}
							<div class="form-group">
						    	<label for="inputname" class="col-sm-2 control-label">Name</label>
							    <div class="col-sm-10">
							      	<input type="text" class="form-control" id="inputname" name="name" value="{{user.username}}" placeholder="Name">
							    </div>
						  	</div>	<!-- End of /.form-group -->
						  	<div class="form-group">
						    	<label for="inputEmail" class="col-sm-2 control-label">Email</label>
							    <div class="col-sm-10">
							      	<input type="email" class="form-control" id="inputEmail" name="email" placeholder="Email">
							    </div>
						  	</div>	<!-- End of /.form-group -->
						  	<div class="form-group">
						    	<label for="inputwebsite" class="col-sm-2 control-label">Website</label>
							    <div class="col-sm-10">
							      	<input type="text" class="form-control" id="inputwebsite" name="website" placeholder="Website">
							    </div>
						  	</div>	<!-- End of /.form-group -->
						  	<div class="form-group">
						    	<label for="inputmessage" class="col-sm-2 control-label">Message</label>
							    <div class="col-sm-10">
							      	<textarea class="form-control" id="inputmessage" name="message" rows="3"></textarea>
							    </div>
						  	</div>	<!-- End of /.form-group -->

							<div class="form-group">
						    	<div class="col-sm-offset-2 col-sm-10">
									<button type="submit" class="btn btn-primary">Send</button>
						    	</div>
						  	</div>	<!-- End of /.form-group -->
						</form>	<!-- End of /.form-horizontal -->
					</div>	<!-- End of /.leave comments -->
				</div>	<!-- End of /.col-md-9 -->

				<div class="col-md-3">
					<div class="blog-sidebar">
						<div class="block">
							<h4>Catagories</h4>
							<div class="list-group">
								<a href="#" class="list-group-item">
									<i class="fa  fa-dot-circle-o"></i>
									Italian Foods
								</a>
								<a href="#" class="list-group-item">
									<i class="fa  fa-dot-circle-o"></i>
									Traditional Food
								</a>
								<a href="#" class="list-group-item">
									<i class="fa  fa-dot-circle-o"></i>
									Indian Food
								</a>
								<a href="#" class="list-group-item">
									<i class="fa  fa-dot-circle-o"></i>
									Spanish Food
								</a>
								<a href="#" class="list-group-item">
									<i class="fa  fa-dot-circle-o"></i>
									Thai FoodN
								</a>
							</div>
						</div>	<!-- End of /.block -->
						<div class="block">
							<h4>Popular Posts</h4>
							{% for obj4 in ob4 %}
							<ul class="media-list">
							 	<li class="media">
							    	<a class="pull-left" href="#">
							      		<img class="media-object" src="{{obj4.image.url}}" alt="...">
							    	</a>
							    	<div class="media-body">
							      		<a href="{% url 'blogapps:article' obj4.id %}" class="media-heading">{{obj4.title}}</a>
							    	  	<p>{{obj4.created_on}}</p>
							    	</div>
							  	</li>
							  </ul>
							{% endfor %}
						</div>	<!-- End of /.block -->

						<div class="block">
							<h4>Tag Cloud</h4>
							<div class="tag-link">
								<a href="">BALLET</a>
								<a href="">BLOG</a>
								<a href="">CHRISTMAS</a>
								<a href="">ELEGANCE</a>
								<a href="">ELEGANT</a>
								<a href="">SHOPPING</a>
								<a href="">SHOP</a>
								<a href="">PHOTOGRAPHY</a>
							</div>
						</div>	<!-- End of /.block -->

					</div>	<!-- End of /.Sidebar -->
				</div>	<!-- End of /.col-md-3 -->
			</div>	<!-- End of /.row -->
		</div>	<!-- End of /.container -->
	</section> <!-- End of /.Section -->

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% include "script.html" %}
    </head>
    <body>
        {% include "header.html" %}
        {% block content %}

        {% endblock content %}
        {% include "footer.html" %}
    </body>
</html>

templates/blogform.html
{% extends "base.html" %}

{% block content %}


<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-10 clearfix">
                <ul class="blog-zone">
                    <li>
                        <div class="blog-icon">
                            <i class="fa  fa-pencil"></i>
                        </div>
                        <div class="blog-box">
                            <div style="width: 700px; height: 700px; margin: auto;">
                                <br>
                                <br>
                                <form action="" method="POST" enctype=multipart/form-data>
                                    <center>
                                        <h3 style="color: lightslategray; font-weight: bolder; font-style: italic; font-family: serif;">Add blogs</h3>
                                        <br>
                                        <br>
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input type="submit" value="save">
                                    </center>
                                </form>
                                <br>
                                <br>
                                <br>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <br>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="cart-title mt-50">
                    <center>
                        <h2 style="font-family: serif; font-weight: bolder; color: slategrey;">Shopping Cart</h2>
                    </center>
                </div>
                <br>
                <br>

                <h6 class="cart-table clearfix">
                    <table class="table table-responsive">
                        <thead>
                            <tr style="background-color: black; height: 50px; color: white; size: 30px; font-size: x-large;">
                                <th></th>
                                <th><br><center>Name</center><br></th>
                                <th><br><center>Price</center><br></th>
                                <th><br><center>Quantity</center><br></th>
                                <th><br><center>Total</center><br></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ob in ob %}
                            <tr>
                                <td class="cart_product_img">
                                    <center><img src="{{ob.title.image.url}}" alt="..." width="120" height="100"></center>
                                </td>
                                <td class="cart_product_desc">
                                    <br><center><h5 style="font-family: serif; font-weight: bolder; color: slategrey;">{{ob.title.title}}</h5></center>
                                </td>
                                <td class="price">
                                    <br><center><h6 style="font-family: serif; font-weight: bolder; color: slategrey;">${{ob.title.price}}</h6></center>
                                </td>
                                <td class="qty">
                                    <span>
                                        <br><center><h6 style="font-family: serif; font-weight: bolder; color: slategrey;">{{ob.quantity}}</h6></center>
                                    </span>
                                </td>
                                <td class="totalprice">
                                    <br><center><h6 style="font-family: serif; font-weight: bolder; color: slategrey;">${{ob.total_price}}</h6></center>
                                </td>
                                <td>
                                    <br>
                                    <center>
                                        <a href="{% url 'textileapp:checkout' ob.title_id %}"><input type="submit" value="Checkout" style="color: lightslategray; font-weight: bolder;"></a>&nbsp;&nbsp;
                                        <a href="{% url 'textileapp:delete_cart' ob.id %}"><input type="submit" value="Remove" style="color: lightslategray; font-weight: bolder;"></a>
                                    </center>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </h6>
            </div>
        </div>
    </div>
<br>
<br>

{% endblock content %}

templates/cartform.html
{% extends "base.html" %}

{% block content %}


<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-10 clearfix">
                <ul class="blog-zone">
                    <li>
                        <div class="blog-icon">
                            <i class="fa  fa-pencil"></i>
                        </div>
                        <div class="blog-box">
                            <div style="width: 700px; height: 700px; margin: auto;">
                                <br>
                                <br>
                                <form action="" method="POST" enctype=multipart/form-data>
                                    <center>
                                        <h3 style="color: lightslategray; font-weight: bolder; font-style: italic; font-family: serif;">Add To Cart</h3>
                                        <br>
                                        <br>
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <a href="{% url 'addtocart' %}" class="btn btn-info btn-lg">
                                            <span class="fa fa-shopping-cart"></span>Continue
                                        </a>
                                    </center>
                                </form>
                                <br>
                                <br>
                                <br>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/form.html
{% extends "base.html" %}

{% block content %}
<div style="width: 350px; height: 400px; margin: auto;">
    <br>
    <br>
    <form action="" method="POST">
        <center>
            <h3 style="color: lightslategray; font-weight: bolder; font-style: italic; font-family: serif;">Add new product</h3>
            <br>
            <br>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="save">
        </center>
    </form>
</div>
{% endblock content %}

templates/header.html
<!-- TOP HEADER Start-->

{% load static %}

<section id="top" style="background-color: lightslategray;">
    <ul class="login-cart">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <p class="contact-action"><i class="fa fa-phone-square"></i>IN CASE OF ANY QUESTIONS, CALL THIS
                        NUMBER:<strong>+565 975 658</strong></p>
                </div> <!-- end of col-md-7 -->
                <div class="col-md-5 clearfix inline">
                    <span>
                    <li>
                        {% if user.is_authenticated %}
                        <p style="font-size:14px;">Welcome {{user.username}} <a href="{% url 'textileapp:logout' %}">Logout</a></p>
                        {% else %}
                        <a data-target="#myModal" data-toggle="modal" href="#">Login</a>
                        {% endif %}
                    </li>
                    <li>
                        <a href="{% url 'textileapp:registration' %}">Registration</a>
                    </li>
                    <li>
                        <div class="cart dropdown">
                            <a href="{% url 'textileapp:cart' %}"><i class="fa fa-shopping-cart"></i>Cart</a>
                        </div>
                    </li>
                    </span>
                </div>  <!-- end of col-md-3 -->
                <div class="col-md-2">
                    <li>
					    <div class="search-box">
						    <div class="input-group">
                                <form action="{% url 'textileapp:search' %}" method="GET" name="myform">
                                    <input name="search" placeholder="Search" type="text"/>
                                </form>
                                {% if messages %}
                                    {% for m1 in messages %}
                                        {{m1}}
                                    {% endfor %}
                                {% endif %}
    					    </div>
				        </div><!-- /.search-box -->
                    </li>
                </div>
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </ul>

    <div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="myModal" role="dialog" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Introduce Yourself</h4>
                </div> <!-- End Of model-header -->

                <div class="modal-body clearfix">

                    <form action="{% url 'textileapp:register' %}" class="std" id="create-account_form" method="post">
                        {% csrf_token %}
                        <fieldset>
                            <h3>Create your account</h3>
                            <div class="form_content clearfix">
                                <p class="text">
                                    <label for="create_username">Username</label>
                                    <span>
                                        <input class="account_input" id="create_username" name="create_username"
                                               placeholder="Enter Username" style="height: auto; padding: 5px; width: 220px; border: 1px solid #dedede;" type="text"
                                               value="">
                                    </span>
                                </p>
                                <p class="text">
                                    <label for="create_password">Password</label>
                                    <span>
                                        <input class="account_input" id="create_password" name="create_password"
                                               placeholder="Enter Password" style="height: auto; padding: 5px; width: 220px; border: 1px solid #dedede;" type="password"
                                               value="">
                                    </span>
                                </p>
                                <p class="text">
                                    <label for="cnfrm_pswd">Confirm password</label>
                                    <span>
                                        <input class="account_input" id="cnfrm_pswd"
                                               name="cnfrm_pswd"
                                               placeholder="Enter confirm password" style="height: auto; padding: 5px; width: 220px; border: 1px solid #dedede;" type="password"
                                               value="">
                                    </span>
                                </p>
                                <p class="text">
                                    <label for="email_create">Email</label>
                                    <span>
                                        <input class="account_input" id="email_create" name="email_create"
                                               placeholder="Enter Email Id" style="height: auto; padding: 5px; width: 220px; border: 1px solid #dedede;" type="email"
                                               value="">
                                    </span>
                                </p>

                                <p class="submit">
                                    <button class="btn btn-primary">Create Your Account</button>
                                </p>
                            </div><!-- End Of form-content -->
                        </fieldset>
                    </form> <!-- End Of form-1 -->

                    {% if user.is_authenticated %}
                    <h1>login</h1>
                    {% else %}
                    <form action="{% url 'textileapp:login' %}" class="std" id="login_form" method="post">
                        {% csrf_token %}
                        <fieldset>
                            <h3>Already registered?</h3>
                            <div class="form_content clearfix">
                                <p class="text">
                                    <label for="username">Username</label>
                                    <span>
                                        <input class="account_input" id="username" name="username"
                                               placeholder="Username" style="height: auto; padding: 5px; width: 220px; border: 1px solid #dedede;" type="text"
                                               value="">
                                    </span>
                                </p>
                                <p class="text">
                                    <label for="passwd">Password</label>
                                    <span>
                                        <input class="account_input" id="passwd" name="passwd"
                                               placeholder="Password" type="password" value="">
                                    </span>
                                </p>
                                <p class="lost_password">
                                    <a class="popab-password-link" href="#popab-password-reset">Forgot your
                                        password?</a>
                                </p>
                                <p class="submit">
                                    <button class="btn btn-success">Log in</button>
                                </p>
                            </div> <!-- End Of form-content -->
                        </fieldset>
                    </form><!-- End Of form-2 -->
                    {% endif %}
                </div> <!-- End Of modal-body -->

                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                </div> <!-- End Of modal-footer -->

            </div> <!-- End Of modal-content -->
        </div> <!-- End Of modal-dialogue -->
    </div> <!-- End Of  modal -->
</section>  <!-- End of Section -->


<!-- LOGO Start -->

<header>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a href="#">
                    <img alt="logo" src="{% static 'images/logo.jpg' %}" style="width: 450px; height: 100px;}">
                </a>
            </div>    <!-- End of col-md-12 -->
        </div>    <!-- End of row -->
    </div>    <!-- End of container -->
</header> <!-- End of Header -->


<!-- MENU Start -->

{% load static %}

<nav class="navbar navbar-default">

    <div class="container">

        <div class="navbar-header">
            <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse"
                    type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div> <!-- End of navbar-header -->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav nav-main">
                <li class="active"><a href="{% url 'textileapp:index' %}">HOME</a></li>
                <li><a href="{% url 'blogapps:blog' %}">BLOG</a></li>
                <li class="dropdown"><a href="#">PAGES<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li> <!-- End of dropdown -->
            </ul> <!-- End of nav-main -->
        </div>    <!-- end of navbar-collapse -->

    </div> <!-- end of container -->
</nav> <!-- End of nav -->


<!-- SLIDER Start -->

<section id="slider-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="nivoSlider" id="slider" style="height: 300px;">
                    <img alt="" height="300" src="{% static 'images/sl1.jpg' %}"/>
                    <img alt="" height="300" src="{% static 'images/sl2.jpg' %}"/>
                    <img alt="" height="300" src="{% static 'images/n2.jpg' %}"/>
                </div>    <!-- End of nivoslider -->
            </div>    <!-- End of col-md-12 -->
        </div>    <!-- End of row -->
    </div> <!-- End of container -->
</section> <!-- End of Section -->


<!-- FEATURES Start
================================================== -->

<section id="features">
    <div class="container">
        <div class="row">

            <div class="col-md-4">
                <div class="block" style="background-color: lightslategray;">
                    <div class="media">

                        <div class="pull-left" href="#">
                            <i class="fa fa-ambulance"></i>
                        </div>

                        <div class="media-body">
                            <h4 class="media-heading">Free Shipping</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur.</p>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="block" style="background-color: lightslategray;">
                    <div class="media">

                        <div class="pull-left" href="#">
                            <i class=" fa fa-foursquare"></i>
                        </div>

                        <div class="media-body">
                            <h4 class="media-heading">Media heading</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur.</p>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="block" style="background-color: lightslategray;">
                    <div class="media">

                        <div class="pull-left" href="#">
                            <i class=" fa fa-phone"></i>
                        </div>

                        <div class="media-body">
                            <h4 class="media-heading">Call Us</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur.</p>
                        </div>    <!-- End of /.media-body -->

                    </div>    <!-- End of /.media -->
                </div>    <!-- End of /.block -->
            </div> <!-- End of /.col-md-4 -->

        </div>    <!-- End of /.row -->
    </div>    <!-- End of /.container -->
</section>    <!-- End of section -->

templates/script.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bold > Boring</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>

    <!-- Css -->
    <link href="{% static 'css/nivo-slider.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

    <!-- jS -->
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.nivo.slider.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
</head>
<body>

</body>
</html>